name: .NET Core

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Upload asset to release
      uses: actions-github/upload-to-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
      # Input file
        file:
          /home/runner/work/VanityKristConsole/VanityKristConsole/bin/Release/netcoreapp3.0/VanityKristConsole.dll
        type: 
          'application/octet-stream'
        # Dry run (true|false)
        dry: 
          false
