name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: ./VanityKristConsole/bin/Release/netcoreapp3.0/VanityKristConsole.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
